services:
  frontend:
    build:
      context: ./frontend/next-ts
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - my-network

  express:
    build:
      context: ./backend/expressjs
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - my-network
    environment:
      - NODE_ENV=development

networks:
  my-network:
